const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nikeslimshirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'NIKE',
      rating: 1.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidasfitshirt',
      category: 'Shirts',
      image: '/images/p2.jpg', //679px * 829px
      price: 180,
      countInStock: 30,
      brand: 'ADIDAS',
      rating: 2,
      numReviews: 15,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Fit Pant',
      slug: 'adidasfitpants',
      category: 'PANTS',
      image: '/images/p3.jpg',
      price: 148,
      countInStock: 8,
      brand: 'NIKE',
      rating: 5,
      numReviews: 20,
      description: 'high quality pant',
    },
    {
      name: 'Puma Fit shirt',
      slug: 'Pumafitshirt',
      category: 'shirts',
      image: '/images/115.jpg',
      price: 148,
      countInStock: 8,
      brand: 'NIKE',
      rating: 3.5,
      numReviews: 20,
      description: 'high quality shirt',
    },
    {
      name: '11 Fit Pant',
      slug: '11fitpants',
      category: '11',
      image: '/images/p3.jpg',
      price: 148,
      countInStock: 8,
      brand: '11',
      rating: 4.5,
      numReviews: 20,
      description: 'high quality pant',
    },
  ],
};
export default data;
