const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nikeslimshirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'NIKE',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit shirt',
      slug: 'adidasfitshirt',
      category: 'Shirts',
      image: '/images/p2.jpg', //679px * 829px
      price: 180,
      countInStock: 30,
      brand: 'ADIDAS',
      rating: 6.5,
      numReviews: 15,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Fit Pant',
      slug: 'adidasfitpants',
      category: 'PANTS',
      image: '/images/p3.jpg',
      price: 148,
      countInStock: 8,
      brand: 'NIKE',
      rating: 8.5,
      numReviews: 20,
      description: 'high quality pant',
    },
    {
      name: 'Puma Fit Pant',
      slug: 'Pumafitpants',
      category: 'PANTS',
      image: '/images/p4.jpg',
      price: 148,
      countInStock: 8,
      brand: 'PUMA',
      rating: 8.5,
      numReviews: 20,
      description: 'high quality pant',
    },
  ],
};
export default data;
